### ISSUE TITLE
Undefined Index

### ISSUE THREAD

**Issue by igabice** [freshbitsweb/laratables#74]
after installation with composer i keep getting "Undefined index: " error message. below is the complete error

using PHP 7.2
Laravel 5.7

{
  "message": "Undefined index: ",
  "status_code": 500,
  "debug": {
    "line": 210,
    "file": "C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\freshbitsweb\\laratables\\src\\ColumnManager.php",
    "class": "ErrorException",
    "trace": [
      "#0 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\freshbitsweb\\laratables\\src\\ColumnManager.php(210): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined index...', 'C:\\\\Users\\\\HP ELI...', 210, Array)",
      "#1 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\freshbitsweb\\laratables\\src\\ColumnManager.php(181): Freshbitsweb\\Laratables\\ColumnManager->getOrderColumn()",
      "#2 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\freshbitsweb\\laratables\\src\\Laratables.php(106): Freshbitsweb\\Laratables\\ColumnManager->getOrderBy()",
      "#3 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\freshbitsweb\\laratables\\src\\Laratables.php(54): Freshbitsweb\\Laratables\\Laratables->fetchRecords()",
      "#4 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\app\\Api\\Controllers\\ClassroomController.php(39): Freshbitsweb\\Laratables\\Laratables::recordsOf('App\\\\Subjects')",
      "#5 [internal function]: App\\Api\\Controllers\\ClassroomController->subjectList()",
      "#6 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): call_user_func_array(Array, Array)",
      "#7 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('subjectList', Array)",
      "#8 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Api\\Controllers\\ClassroomController), 'subjectList')",
      "#9 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(176): Illuminate\\Routing\\Route->runController()",
      "#10 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(682): Illuminate\\Routing\\Route->run()",
      "#11 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#12 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\dingo\\api\\src\\Http\\Middleware\\PrepareController.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#13 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Dingo\\Api\\Http\\Middleware\\PrepareController->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
      "#14 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#15 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#16 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(684): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
      "#17 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Dingo\\Api\\Http\\Request))",
      "#18 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(625): Illuminate\\Routing\\Router->runRoute(Object(Dingo\\Api\\Http\\Request), Object(Illuminate\\Routing\\Route))",
      "#19 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute(Object(Dingo\\Api\\Http\\Request))",
      "#20 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\dingo\\api\\src\\Routing\\Adapter\\Laravel.php(81): Illuminate\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
      "#21 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\dingo\\api\\src\\Routing\\Router.php(512): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')",
      "#22 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(126): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
      "#23 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#24 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#25 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
      "#26 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#27 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
      "#28 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#29 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
      "#30 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#31 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
      "#32 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#33 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
      "#34 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\barryvdh\\laravel-cors\\src\\HandlePreflight.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#35 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Barryvdh\\Cors\\HandlePreflight->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
      "#36 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#37 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
      "#38 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\dingo\\api\\src\\Http\\Middleware\\Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))",
      "#39 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
      "#40 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
      "#41 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
      "#42 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
      "#43 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))",
      "#44 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))",
      "#45 C:\\Users\\HP ELITEBOOK\\PhpstormProjects\\sams\\server.php(21): require_once('C:\\\\Users\\\\HP ELI...')",
      "#46 {main}"
    ]
  }
}

**Comment by gauravmak** [comment]
Hi @igabice 

Which version of datatables are you using?

**Comment by igabice** [comment]
I'm using version 2

**Comment by gauravmak** [comment]
Is version 2 released? - I can't find here: https://cdn.datatables.net/releases.html

**Comment by igabice** [comment]
sorry I'm using 1.10.19

**Comment by gauravmak** [comment]
Can you please share the request URL with query parameters that datatables is using to fetch data?

You can get that using `chrome devtools -> network tab`

![Screenshot from 2019-11-19 09-34-54](https://user-images.githubusercontent.com/11887260/69118073-1624eb80-0ab8-11ea-831d-f116c110b361.png)

**Comment by gauravmak** [comment]
Closing due to inactivity
